export const people = [
  {
    name: 'Ravein Sharma',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Nidhi Gupta',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Shivangi Gupta',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Preeti Dudi',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Ritik Raj',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Harsh Raghuvanshi',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Satvik Sharma',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Nikita Gupta',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Saksham Gupta',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Ankush Bhamra',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Vineet Kumar',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
  {
    name: 'Eshan Mahajan',
    profileURL: '',
    requestStatus: '',
    balance: '',
    currency: '',
    countryCode: '',
    contactNumber: '',
  },
];

export const screens = {
  SplashScreen: 'SplashScreen',
  MainScreen: 'MainScreen',
  RequestScreen: 'RequestScreen',
  SearchScreen: 'SearchScreen',
};
